name: injegun_sosik
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  cloud_firestore: ^6.1.2
  cached_network_image: ^3.3.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  share_plus: ^10.1.2
  in_app_review: ^2.0.11
  flex_seed_scheme: ^3.6.1
  flutter_local_notifications: ^20.1.0
  google_mobile_ads: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^8.0.2
  swipeable_page_route: ^0.4.8
  flutter_html: ^3.0.0
  google_maps_flutter: ^2.14.2
  upgrader: ^12.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  freezed: ^3.2.3
  json_serializable: ^6.11.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#5F8F3C"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
