// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnzj_qEWtStUflb3rMiIhbGGO1GuA2jTw',
    appId: '1:611026964031:web:92cf4bba6189e8c54a728a',
    messagingSenderId: '611026964031',
    projectId: 'injegun-sosik',
    authDomain: 'injegun-sosik.firebaseapp.com',
    storageBucket: 'injegun-sosik.firebasestorage.app',
    measurementId: 'G-LGWQPR0W5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xaBYqLlx7lCAjRttWsrnUNJe1KC7oIE',
    appId: '1:611026964031:android:a43d058c38bbacd44a728a',
    messagingSenderId: '611026964031',
    projectId: 'injegun-sosik',
    storageBucket: 'injegun-sosik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9KvJQCehvYbc215GVGVDRXiaaZjXVrK4',
    appId: '1:611026964031:ios:58ba739a09e47ca44a728a',
    messagingSenderId: '611026964031',
    projectId: 'injegun-sosik',
    storageBucket: 'injegun-sosik.firebasestorage.app',
    iosBundleId: 'com.jylee.injegun.sosik',
  );

}